.\" Manpage for fibonacci.
.\" Contact Elijah Harmon to correct errors or typos.
.TH fibonacci 1 "5 May 2018" "1.0" "User Commands"
.SH NAME
fibonacci \- print the fibonacci number for any number between 0-100
.SH SYNOPSIS
USAGE: ./fibonacci [OPTIONS] NUMBER
.SH DESCRIPTION
Fibonacci takes a number (0-100) via the command line and output's the fibonacci number related to the number.

By default, the output is in HEX. The -o flag can be set to get the output in OCTAL.

.SH OPTIONS
.TP
.BR \-o
Output will be in OCTAL


.SH BUGS
No known bugs.
.SH AUTHOR
Elijah Harmon